### ISSUE TITLE
Generate certificate after DAB Purchase

### ISSUE THREAD

**Issue by paulstroot** [ocupop/comission-shopify-hydrogen#59] opened 2022-09-12 16:49 UTC
Generate PDF certificate after DAB Purchase.

_Originally posted by @paulstroot in https://github.com/ocupop/comission-shopify-hydrogen/issues/29#issuecomment-1244016624_

Once the PDF is created, the order status will be changed to "Fulfilled". A fulfilled order will display the "Download Certificate" and "Print Certificate" buttons in the order history.

**Comment by tbeck** [comment] 2022-09-12 20:29
- [ ] Landscape layout
- [ ] Need character limits for Museum note

**Comment by jennyvanderheiden** [comment] 2022-09-15 21:27
@ZiggyAtl  -  Check out these two orientations for the certificate and let us know what you are feeling! Thank you

https://www.dropbox.com/s/65sxqy582v50ao8/comission-certificate-thatillustriousfeeling-v2.pdf?dl=0

**Comment by ZiggyAtl** [comment] 2022-09-16 17:43
Thanks for that Jenny. I think these are both a big improvement on the first draft. As I mentioned yesterday, I think all the information which was previously on it was required, and I was looking for us to increase the % of the page taken up by the art at the expense of the white space, so I think both do that. However I've noticed that the wording describing the cause that the DAB is supporting is now not on there, or the museum logo, and I think both those need to be on. A couple of other things;
I think whatever we go with should only have a minimal margin, so the margins in both designs could be reduced.
On the portrait one, the CoM logo could be in the top right in line with the title (and maybe reduce the title type height a touch to accommodate that). That would then allow the overall design to be increased proportionately in size. 
On the landscape one the CoM logo could be moved to the left, to reduce that white space to the right on the block below which contains the DAB and the content.
As you rightly said before, portrait or landscape is more of a personal choice on things like this. One thought, is it possible to keep both configurations so that the user could choose whether they wanted it portrait or landscape?

**Comment by ZiggyAtl** [comment] 2022-09-16 19:42
Also, could you make a couple of modifications please;
Change the title to "Certificate of Authenticity"
Change 'Unique DAB #' to just 'DAB #'
Change 'DAB Collector' to just 'Collector'
Thanks

**Comment by jennyvanderheiden** [comment] 2022-09-19 13:31
I will work on the next version. I don't recommend offering 2 versions... I definitely think that the landscape version offers more real estate for the details you want. I don't think we should infringe too much on the margin on the landscape if people are indeed to print this out. The vertical version for sure has margins that are wider because the information needed to fit with the increase of the painting size. Also want to emphasize what we mentioned in the call that this example is square and other sizes may impact the layout leaving white spaces where there are none here. 

I will make those modifications and alter the layout and we can see how it is working from there

**Comment by ZiggyAtl** [comment] 2022-09-19 13:36
OK thanks. Maybe another use people might find for a landscape version is as a screen saver

**Comment by ZiggyAtl** [comment] 2022-09-20 15:43
Not in a position where I can print it out and see what it looks like other than on my laptop. Would like to see that before signing off. But initially it looks good. I agree with what you're saying about the landscape being more adaptable, and take on board your thoughts about not needing 2 orientations.

**Comment by alexjlahr** [comment] 2022-10-03 18:43
@jennyvanderheiden Flagging for your reference in case its needed here.

**Comment by paulstroot** [comment] 2022-10-14 17:51
@jonathanwburr , I'm assigning this to you if you have time. If I get an opening next week before you do I can tackle it too, but I have a handful of higher priorities on my to-do list.

**Comment by paulstroot** [comment] 2022-10-18 17:22
Update of the certificate design is complete. Here is a direct link to one of the certificates for review:
https://store.comission.art/dab/certificate/7273907388595-3Y5xssYHZEK3mNs9Av2Z
(you man need to decrease the size of your browser window to make it fit.)

**Comment by ZiggyAtl** [comment] 2022-10-18 18:41
Hi @paulstroot we had landed on the landscape version of this but it appears to be landscape. Also when I went to print it, it didn't fit on a regular page (I had to reduce the scale). And please can it have the color version of the CoM logo, not the black and white

**Comment by paulstroot** [comment] 2022-10-18 18:45
Yes, it is landscape. Users will ideally print from the PDF that we will be generating, not from the browser, so it should fit perfectly when it is printed.

I overlooked the color of the logo, thanks. I'll have that updated soon.

**Closed** 2022-10-20 17:27 UTC
Labels: ready for review
