### ISSUE TITLE
Update cart to include "remove" functionality

### ISSUE THREAD

**Issue by tbeck** [ocupop/comission-shopify-hydrogen#126] opened 2022-10-17 19:52 UTC
...once I get to the checkout I can't update the items in my cart. I realized there was already a DAB in there from the last time I had visited, and as a user I would then have wanted to delete one. However it doesn't allow me to delete anything that's in the cart, and I think it should be able to do that. 

_Originally posted by @ZiggyAtl in https://github.com/ocupop/comission-shopify-hydrogen/issues/96#issuecomment-1281070110_

**Comment by paulstroot** [comment] 2022-10-18 16:53
@ZiggyAtl - This is pretty standard checkout procedure for most e-commerce. Users can make edits to their products when they are viewing their cart, and once they click "Checkout", that solidified the products they want to buy and continues on to the payment process. They need to go back to their cart if they want to edit the products they want to purchase.

**Comment by paulstroot** [comment] 2022-10-18 17:20
... Also @ZiggyAtl , just to confirm, the title of this issue is "Update Cart to include remove...", but in your description you refer to the checkout page. These are two separate pages, which one do you mean?

**Comment by ZiggyAtl** [comment] 2022-10-18 18:33
@paulstroot Sorry, I was referring to be able to remove something from the cart please. I take on board what you say about the checkout procedure and that makes sense, however it also needs the ability to go back to the cart from the checkout, if someone sees they need to add or delete something. And I couldn't see how to do that either.

**Comment by paulstroot** [comment] 2022-10-20 12:38
@ZiggyAtl , if I'm understanding correctly, what we're talking about here is giving users the ability to navigate back from the checkout page to their cart, where they can then edit their cart items, correct? If so, then I believe this issue is a duplicate of #137

**Comment by ZiggyAtl** [comment] 2022-10-20 13:17
@paulstroot you're right in this has some duplication with #127   Would the link back from the checkout to the cart also give the user access back to the site too, in case they wanted to check something about the art, or maybe add something else? If that is the case, then yes #127 and #126 can be merged as one issue.

**Comment by paulstroot** [comment] 2022-10-20 18:01
Duplicate of #127

**Closed by paulstroot** 2022-10-20 18:01 UTC
Labels: question
